export default {
  endOfLine: "lf",
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(react-dom/(.*)$)|^(react-dom$)",
    "^(react-router-dom/(.*)$)|^(react-router-dom$)",
    "",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/config/(.*)$",
    "^@/types/(.*)$",
    "^@/api/(.*)$",
    "^@/lib/(.*)$",
    "^@/routes/(.*)$",
    "^@/components/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/layouts/(.*)$",
    "^@/hooks/(.*)$",
    "^@/stores/(.*)$",
    "^@/utils/(.*)$",
    "^@/assets/(.*)$",
    "^@/styles/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  tailwindConfig: "./tailwind.config.ts",
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
};
